name: signature
description: A Flutter plugin providing performance optimized signature canvas with ability to set custom style, boundaries and initial state.
version: 5.3.0
homepage: https://github.com/4Q-s-r-o/signature

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.1+1
  image: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: