name: signature
description: A Flutter plugin providing performance optimized signature canvas with ability to set custom style, boundaries and initial state.
version: 5.4.1
homepage: https://github.com/4Q-s-r-o/signature

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.0+1
  image: ^4.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: